services:
  martin:
    image: ghcr.io/maplibre/martin:latest
    container_name: martin
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./martin/config.yaml:/config.yaml
      - ./martin/tiles:/tiles
      - ./martin/sprites:/sprites
    command: ["--config", "/config.yaml"]
    healthcheck:
      disable: true 

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/var/cache/nginx
    depends_on:
      - martin
    entrypoint: /bin/sh -c "rm -rf /var/cache/nginx/* && exec /docker-entrypoint.sh nginx -g 'daemon off;'"

volumes:
  nginx_cache: